language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov
    - python setup.py develop
# command to run tests
script: python -m pytest tests/ --cov=.
after_success:
    - coveralls
